### ISSUE TITLE
The blog title in every page?

### ISSUE THREAD

**Issue by pireddag** [texmacs/notes#10]
It might be good that every page has "A TeXmacs blog" in its header.

**Comment by mgubi** [comment]
I've changed the main title to "Notes on TeXmacs" :)

**Comment by pireddag** [comment]
Ok. I meant the header with the title (that now is "Notes on TeXmacs") rather than only an icon in the header of every page.

**Comment by mgubi** [comment]
Ah, I misunderstood. Actually I like it that way, very minimal. (It could be good to have a small and non-intrusive header for the pages, but I still have to think about it).

**Comment by pireddag** [comment]
Ok. I sent the link to only one page to an previous colleague of mine, and it feels like he should read the name of the blog in the header (so he knows that this is a blog on TeXmacs).

**Comment by mgubi** [comment]
Added a running title.
