### ISSUE TITLE
Can't open "https://texmacs.github.io/notes/" 

### ISSUE THREAD

**Issue by uno55555** [texmacs/notes#34]
Recently, I can not open the website and https://texmacs.github.io/notes/. I have forked the whole project and I have setted up my own website. But in the past few days, I can not open any website including the official. What happened? 
Hope someone can give me an answer! Thanks!

**Comment by mgubi** [comment]
It works normally for me.

**Comment by da-liii** [comment]
There is a mirror: https://gitee.com/texmacs/notes

And the corresponding website: https://texmacs.gitee.io/notes/docs/main.html
