### ISSUE TITLE
Output of update-website

### ISSUE THREAD

**Issue by pireddag** [texmacs/notes#37]
The article list, if I run update-website, lists the time-zone as GMT.

This is what I understand right now.
Guile's `gmtime` calls the C `gmtime` function. I have looked into the C sources for the time library, and I understood this: `gmtime` calls `__tz_convert` with `use_localtime` set to `0`; then the following assignment is executed: `tp->tm_zone = "GMT";`

How is it that in the article list in the website time zones are UTC?

**Comment by mgubi** [comment]
On my MacOS I can run the following from the command line
```
guile> (strftime "%c %Z"  (gmtime (current-time)))
"Tue Mar 16 20:09:28 2021 UTC"
```
in Guile 1.8.8. Which version of Guile do you use?

**Comment by mgubi** [comment]
Maybe one can enforce a system independent time zone as follows
```
(strftime "%c %Z"  (localtime (current-time) "UTC"))
```
I'm not sure what is appropriate for that file.

**Comment by pireddag** [comment]
System-wide I am using 2.2.7, but I tried from TeXmacs

```
(begin (setenv "TZ" "UTC")
       (setenv "LC_ALL" "POSIX")
       (strftime "%c %Z"  (gmtime (current-time))))
```

and I get

 `"Tue Mar 16 20:19:23 2021 GMT"`

**Comment by mgubi** [comment]
The guile function is as follows (in `libguile/stime.c`)
```
SCM_DEFINE (scm_gmtime, "gmtime", 1, 0, 0,
            (SCM time),
	    "Return an object representing the broken down components of\n"
	    "@var{time}, an integer like the one returned by\n"
	    "@code{current-time}.  The values are calculated for UTC.")
#define FUNC_NAME s_scm_gmtime
{
  timet itime;
  struct tm bd_buf, *bd_time;
  const char *zname;

  itime = SCM_NUM2LONG (1, time);

  /* POSIX says gmtime sets errno, but C99 doesn't say that.
     Give a sensible default value in case gmtime doesn't set it.  */
  errno = EINVAL;

#if HAVE_GMTIME_R
  bd_time = gmtime_r (&itime, &bd_buf);
#else
  SCM_CRITICAL_SECTION_START;
  bd_time = gmtime (&itime);
  if (bd_time != NULL)
    bd_buf = *bd_time;
  SCM_CRITICAL_SECTION_END;
#endif
  if (bd_time == NULL)
    SCM_SYSERROR;

#if HAVE_STRUCT_TM_TM_ZONE
  zname = bd_buf.tm_zone;
#else
  zname = "GMT";
#endif
  return filltime (&bd_buf, 0, zname);
}
#undef FUNC_NAME
```
So maybe in your system `HAVE_STRUCT_TM_TM_ZONE` is undefined.

**Comment by mgubi** [comment]
Note that `setenv` will set the variables for the whole process, I do not think it is the appropriate way to do.

**Comment by pireddag** [comment]
> Note that `setenv` will set the variables for the whole process

Ok but for a quick check it is fine ;-)

**Comment by mgubi** [comment]
Given these differences I think is better we use `localtime` with an explicit `UTC` time zone for the file.

**Comment by pireddag** [comment]
The macro variable  `HAVE_STRUCT_TM_TM_ZONE` seems to be defined using the `_LIBC` one, which I did not figure out how it takes up a value. Do you know?
I looked at  the code of guile's `localtime` and I did not understand the details, but using it with an explicit `UTC` time zone gave the "right" result so I am guessing it is fine ;-)

**Comment by pireddag** [comment]
I suspect this https://stackoverflow.com/questions/2864561/defining-libc-in-c-program has something to do with the `_LIBC` which my system does not have, but I am unable to see quickly deeper.

**Comment by mgubi** [comment]
If you compiled guile 1.8.8 from source then you should have there a `config.h` file generated from `config.h.in` and in my copy there is 
```
/* Define to 1 if `tm_zone' is a member of `struct tm'. */
#define HAVE_STRUCT_TM_TM_ZONE 1
```
I would guess that in your system this variable is `#undef`, or not?

**Comment by pireddag** [comment]
I compiled neither guile 1.8.8 nor 2.2.7. I got 1.8.8 from the static binary of TeXmacs, and I installed 2.2.7 from the Ubuntu repositories.

I looked quickly again at compilation flags to remind myself how it works. In `gcc`, `-D name=definition` in compilation allows controlling compilation with preprocessor macros where the value is set by the flag (I found it in https://stackoverflow.com/questions/5302390/is-it-possible-to-define-a-c-macro-in-a-makefile). I assume (did not check) that `-D name=definition` can use an environment variable for `definition`, in this case `HAVE_STRUCT_TM_TM_ZONE`.
In my computer that is undefined---the same would be if the "critical" variable would be ` _LIBC`, which is also undefined in my system.

And, finally, since I installed binaries that does not have an effect :-)

**Comment by mgubi** [comment]
If you cannot inspect the sources then it is not clear what where the options when your version of guile 1.8.8 has been compiled (they are decided when `configure` runs). If you really what to check what is going on, you should try to build guile and see what are the options there, if `HAVE_STRUCT_TM_TM_ZONE` is not defined by `configure` (in guile I mean, not in TeXmacs) then the default timezone for the `gmtime` scheme function will be `GMT` as per the code I posted above.

**Comment by mgubi** [comment]
> In my computer that is undefined---the same would be if the "critical" variable would be ` _LIBC`, which is also undefined in my system.

We are not talking of environment variables, but of `C preprocessor definitions`: they exists only when compiling C files, usually defined in some header file like `config.h` generated by running `configure`. This allow source files to adapt to the various OS they are compiled in (not all the Unix have compatible system calls...)

**Comment by pireddag** [comment]
> If you cannot inspect the sources

I checked a Guile that I have in another side of my system (I made an account to experiment time ago), and that has `HAVE_STRUCT_TM_TM_ZONE` equal to `1` in its `config.h`.
But given that at least one TeXmacs, the Linux static binary, does not support that, I think it is wise not rely on that.

**Comment by mgubi** [comment]
I've modified the source of the update tool to use explicitly "UTC". Now it is guaranteed to work in any system. I close this issue.
